GET http://localhost:5000 HTTP/1.1

###
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "Vinhvinhvi",
    "password": "vinh"
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "Vinhvinhvi",
    "password": "vinhvinh"
}

###
PUT http://localhost:5000/api/auth/61dede4dd2ca2fadc7e5393b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWRlZGU0ZGQyY2EyZmFkYzdlNTM5M2IiLCJpYXQiOjE2NDE5OTc5Mjd9.ElBd5UZJ_7-BVEMtgnTtWfQzsM8_R_bDOdoBT77jdt4

{
    "username": "Vinhvinhvi",
    "password": "vinh",
    "newpassword": "vinhvinh"
}

###
POST http://localhost:5000/api/note HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE2MTkxMGRhZjQ4MDBjMjg1NjI5ZmMiLCJpYXQiOjE2NDE5OTU3Nzl9.6KLji3IPOJcLVwtFFvpFEy8j56negIlIj3xxOc5M-lg


{
    "title": "Vinh hihihel",
    "description": "abc",
    "deadline": "2015-12-24"
}

###
GET http://localhost:5000/api/note HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE2MTkxMGRhZjQ4MDBjMjg1NjI5ZmMiLCJpYXQiOjE2Mzk5Nzg3NjZ9.DmbtYsLwXVMrQ--jodpDn2w-2FZYTagUsZulqCIcFJQ


###
PUT http://localhost:5000/api/note/61a61efc9b5c0cef3f2baffb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE2MTkxMGRhZjQ4MDBjMjg1NjI5ZmMiLCJpYXQiOjE2MzgzMzYwNDN9.zi7QJBqENvneEBRBzTSM36AtuXRiLRzkE936Ad7bI3M

{
    "title": "Vinh welcome",
    "description": "abc"
}

###
DELETE http://localhost:5000/api/note/61a61efc9b5c0cef3f2baffb HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE2MTkxMGRhZjQ4MDBjMjg1NjI5ZmMiLCJpYXQiOjE2MzgzMzYwNDN9.zi7QJBqENvneEBRBzTSM36AtuXRiLRzkE936Ad7bI3M

###
POST http://localhost:5000/api/group/createGroup HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE2MTkxMGRhZjQ4MDBjMjg1NjI5ZmMiLCJpYXQiOjE2NDEyODc4MTR9.JB7CuQHmfCflqa_0lEYucAHvW3UWyPlLYN7shxLSjDk

{
    "groupname": "Vinh's group",
    "code": "2006trang"
}

###
GET http://localhost:5000/api/group/loginGroup HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE2MTkxMGRhZjQ4MDBjMjg1NjI5ZmMiLCJpYXQiOjE2NDEyODc4MTR9.JB7CuQHmfCflqa_0lEYucAHvW3UWyPlLYN7shxLSjDk

{
    "code": "2006trang"
}